// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// KeepRequest defines model for KeepRequest.
type KeepRequest struct {
	// Prompt The base prompt you want to build a keep for
	Prompt string `json:"prompt"`

	// RandomiseXmlTag Whether to randomise the XML tag that is used to escape user input in your prompt.
	RandomiseXmlTag *bool `json:"randomise_xml_tag,omitempty"`
}

// KeepResponse defines model for KeepResponse.
type KeepResponse struct {
	// ShieldedPrompt The shielded prompt.
	ShieldedPrompt string `json:"shielded_prompt"`

	// XmlTag The XML tag that is used to escape user input in your prompt.
	XmlTag string `json:"xml_tag"`
}

// User defines model for User.
type User struct {
	// UserId The user ID of the suspicious user.
	UserId *string `json:"userId,omitempty"`
}

// WallRequest defines model for WallRequest.
type WallRequest struct {
	// CheckBadwords Whether to scan for badwords in the prompt.
	CheckBadwords *bool `json:"check_badwords,omitempty"`

	// FastCheck Whether to perform a fast check on the prompt instead of a full check.
	FastCheck *bool `json:"fast_check,omitempty"`

	// Prompt The text prompt to be verified.
	Prompt string `json:"prompt"`

	// ScanPii Whether to scan for PII in the prompt.
	ScanPii *bool `json:"scan_pii,omitempty"`

	// SessionId The session ID of the user who is submitting the prompt. This is used to flag suspicious sessions
	SessionId *string `json:"session_id,omitempty"`

	// UserId The user ID of the user who is submitting the prompt. This is used to flag suspicious users
	UserId *string `json:"user_id,omitempty"`

	// XmlTag The XML tag that is used to escape user input in your prompt (this may have been generated with keep).
	XmlTag *string `json:"xml_tag,omitempty"`
}

// WallResponse defines model for WallResponse.
type WallResponse struct {
	// ContainsPii Whether the prompt contains PII.
	ContainsPii *bool `json:"contains_pii,omitempty"`

	// PotentialJailbreak Whether the prompt contains a potential jailbreak.
	PotentialJailbreak *bool `json:"potential_jailbreak,omitempty"`

	// PotentialXmlEscaping Whether the prompt contains potential XML escaping.
	PotentialXmlEscaping *bool `json:"potential_xml_escaping,omitempty"`

	// SuspiciousSession Whether the session is suspicious.
	SuspiciousSession *bool `json:"suspicious_session,omitempty"`

	// SuspiciousUser Whether the user is suspicious.
	SuspiciousUser *bool `json:"suspicious_user,omitempty"`
}

// BuildKeepJSONRequestBody defines body for BuildKeep for application/json ContentType.
type BuildKeepJSONRequestBody = KeepRequest

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody = User

// BuildWallJSONRequestBody defines body for BuildWall for application/json ContentType.
type BuildWallJSONRequestBody = WallRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Improve your prompts security with instruction defense
	// (POST /keep)
	BuildKeep(w http.ResponseWriter, r *http.Request)
	// List Suspicious Users
	// (GET /user)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Add Suspicious User
	// (POST /user)
	AddUser(w http.ResponseWriter, r *http.Request)
	// Remove Suspicious User
	// (DELETE /user/{userId})
	RemoveUser(w http.ResponseWriter, r *http.Request, userId string)
	// Get Suspicious User
	// (GET /user/{userId})
	GetUser(w http.ResponseWriter, r *http.Request, userId string)
	// Verify a Prompt
	// (POST /wall)
	BuildWall(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Improve your prompts security with instruction defense
// (POST /keep)
func (_ Unimplemented) BuildKeep(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Suspicious Users
// (GET /user)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Suspicious User
// (POST /user)
func (_ Unimplemented) AddUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove Suspicious User
// (DELETE /user/{userId})
func (_ Unimplemented) RemoveUser(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Suspicious User
// (GET /user/{userId})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify a Prompt
// (POST /wall)
func (_ Unimplemented) BuildWall(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// BuildKeep operation middleware
func (siw *ServerInterfaceWrapper) BuildKeep(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BuildKeep(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AddUser operation middleware
func (siw *ServerInterfaceWrapper) AddUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RemoveUser operation middleware
func (siw *ServerInterfaceWrapper) RemoveUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, chi.URLParam(r, "userId"), &userId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, chi.URLParam(r, "userId"), &userId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// BuildWall operation middleware
func (siw *ServerInterfaceWrapper) BuildWall(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BuildWall(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/keep", wrapper.BuildKeep)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/user", wrapper.AddUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/user/{userId}", wrapper.RemoveUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user/{userId}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/wall", wrapper.BuildWall)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZb2/bvhH+KgQ3YBtgx0nTrp1eLUGBwmiLBU26DCgC4yyeLDYSyZInO17g7z4cJfm/",
	"4xhN2uGHvIsl6u743PPcHZl7mdrSWYOGgkzuZUhzLCH++RHRfcEfFQbin85bh540huZX6eJzhSH12pG2",
	"RibyKkcxhICiXiCmthITMCTIimGlCyVA3CI6kVkvO5KmDmUiA3ltRnLWkR6MsqUOOLgriwHBaNPFdY6U",
	"o2eL89WCchT/+fxJEIwE5UBCB1EFVLwKQwoO+acX2riKhDYcmG+CPFoEMrS2QDByxqHgj0p7VDL51m73",
	"Zr7QDr9jShxxDVNw1gTcxCnkGguFavAQYO2izXgWwOyE4+ppdt56Wtv4evyLQLZh8TWg38SA3ffV9shj",
	"aP33wmYxhaEKTqfaVnEPfnt8G26voSh2MjXNMb0dDEFNrFfhQTqFFAwTU7SrGS4OazdPOjKDQIPo5EHb",
	"Dn1mfSlA8AcifiDssnmhTSAExViAyKqiqFdtd/sQnwjvqDXKukMxRq8zjWortXjbA6f147C56PcfA0vA",
	"ELQ1A70j8c37pdxHKkxyywQO1bDURNqMlh2Jq1yHZX5nBYyWOdMYDdt2yeZ3RrNGwycIhU2EXyZk8Vfi",
	"eEqYihzGKIaIRozQoAdCJSaa8lh2/7Zf8Q+Uulpnu0pdag2BNmEPlRZ8bz9gSu0guSU0pKEYfAddDD3C",
	"7WGWQcxNiLmJfb44QxFwhucgdwtnnMjWxg6BzLkyaGj7sK9WMJGS7ad7TVdNRd5tt+bUPqObZTdqPK28",
	"puklDw01Cc6c/ojTs4ryTa9nF31xi1PRsi2Wk7PrS8EvPgDhBKayIzWvzREU8oRgoGSvd11wunuL00Vs",
	"EF3JGUeiTWbnHExjWcQSdMHLVKnNPwNkSNZX5ii15cLsZeWc9ZHcq7FexMy+xwyNQv+XEGN03o61QqZV",
	"iWkORocy1kby2sXCCEY1pZ33Nq/rjJi2piPQhIpVJzieeZ1OObUNTzQVuOFfdOfW6xei39oU/46lPYX4",
	"4xL9WKcoO3KMvuaUPDk6PjrmHVqHBpyWiTyNjzrSAeUxbT0uDlHSNmxtKjoINMpZbUhAmqIjRmGp0XRq",
	"FKKYOwscgtC0AwuPVHnDYIBZPBchtR4ZCq4tcVc8O8hzHh551pJ1ucJA51ZN26SjiWGDc0WDRe97qCVV",
	"j7T81589ZjKRf+otZt5eM/D2lqfd2WpNJF9hfFBXvgjYq+PjJ3bdlNXoexX9yyplhmRVIeaYHHFCX9dB",
	"rK4+ByUagLhLzYtUxoMcC73UkW3CcisZQ6FVNPZmm7G+IfQGChHQj9EL9N76oxXxy+Tbquy/3cxuuAaV",
	"Jfgp2yhZN7jcrrhT11/XrYknH1/V+VfM+cAUvutCCf+1hqU/qstDVxvCUQ0BR5sTuc9IuWWKXPzr8iqS",
	"OgTKva1G+TnmMNbWy0ROcjQDYwclUJovFZFJ4NH2jutK5Vkb4E0Ck5AsnCZYdScYqHuSFFAOFSSsm96r",
	"45M33ePT7ulJL6tMDD702q+bhYsvX79994+T47+/PX13epq065MMgSqPXVBKm1HXgB5jd1X7XaZHT5ux",
	"rckV4hCxBZom6d2YUqC4a54iY7Z6bSMY4V5918JkfRc6EM9E63PNpjw/6UBfm5Hnp4SiCcuwTzHxnLFo",
	"SeA9TA9SzrORnXEQlwu4WkxeuBy5zHCscjlOXo/oOUoxIeOwQjYOLo8n55lSkTHP0zlqMj6mZZxs7pI/",
	"FmFO02LKO0V1QHmPkCgg+B21/Uypdba/kP0BsreVuHdfX4rM6rQUSLi/Kpd2jHMRZN6WB8rgS7TQ5MiB",
	"hxKJqxMnOQ7djM5iNm6ubdZp3VmSxfpJ8mZ78d9H+Xprh5K+/1ummRrEF9IfVOEPGjqCw5RPNNsuA1cJ",
	"/QHpN7D5iZvGo2f91zukZCyfsCrzzMT/gPTC+gNL/QSK4v//VH3NUT7PbLR8M/+LT9Url5V/vFN1vPaZ",
	"CmguhF6k2EqR8/6Tx+WYB85M3U02bgZVc1VRL4pQFDKJ6Iak12v+RbB65cjZe1QYUQgxkOReNk/xy7I2",
	"67619upiqQNGac1m/wsAAP//NjUilNwdAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
